name: Run Certik Bot

on:
  schedule:
    - cron: '0 6 * * *'   # 08:00 по Брюсселю
    - cron: '0 8 * * *'   # 10:00 по Брюсселю
    - cron: '0 12 * * *'  # 14:00 по Брюсселю
  workflow_dispatch:

jobs:
  run-certik:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python3 send_daily_update.py

